### ISSUE TITLE
the newer nrf toolbox app requires init packet file (.dat)

### ISSUE THREAD

**Issue by TheDewser** [adafruit/Adafruit_BluefruitLE_Firmware#1]
So I am fairly new to this sort of thing, it does not appear that this file is available with the downloaded zip from Nordic, so I am guessing it has to be created.  The instructions on Nordic's site about creating a file are sort of cryptic to me.

**Comment by microbuilder** [comment]
The .init files are available in the firmware folder for every release (*init.dat).  For example: https://github.com/adafruit/Adafruit_BluefruitLE_Firmware/tree/master/0.6.5/blespifriend
