### ISSUE TITLE
Support for more than 30 characteristics

### ISSUE THREAD

**Issue by collin80** [adafruit/Adafruit_BluefruitLE_Firmware#12]
I realize that some people believe 30 characteristics to be a whole lot. I do not. I have found ways to pack values into structs and pass them that way but it has limited the utility of descriptors. If I had more characteristics I could send each piece of data in a separate characteristic and define it with exponent and the unit. That would allow my characteristics to be more open. Then other apps could easily consume data from my project without having to get struct definitions ahead of time. Is this possible with the current hardware?

**Comment by ladyada** [comment]
chances of this happening is basically nil - please figure out how to use what we've got :)

**Comment by collin80** [comment]
Thanks for the reply. It's what I expected. But, I had to try!
