### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by gfwilliams** [adafruit/Adafruit_BluefruitLE_Firmware#14]
Hi - is the source code for this available?

If so, please could you add a link to the README in this repository? It might be helpful to others... thanks!

**Comment by microbuilder** [comment]
We're unable to publish the source code due to license terms from Nordic.

**Comment by gfwilliams** [comment]
Sorry - should have checked the closed issues: https://github.com/adafruit/Adafruit_BluefruitLE_Firmware/issues/7
