### ISSUE TITLE
BETA 0.8.0 firmware solves a number of problems but...

### ISSUE THREAD

**Issue by fnocci** [adafruit/Adafruit_BluefruitLE_Firmware#21]
Beta 0.8.0 has been in beta for 6 months, and it seems to solve (for some) the "couldn't factory reset" problem on the Feather Bluefruit 32u4 and M0 boards:

https://forums.adafruit.com/viewtopic.php?f=57&t=122726&start=15#p625126

and 

https://forums.adafruit.com/viewtopic.php?f=57&t=106888&p=658252#p658152

What I'm hoping will happen is that 0.8.0 is tested to the point that it can be reliably used in production, i.e. waiting for 0.8.1 -- thanks!  

I'll keep updating the forum posts with reliability info, as we're hoping to be able to use these in production.  Thanks!

**Comment by microbuilder** [comment]
This should probably go into production. We didn't get entirely consistent feedback from some people with the issues this release tries to solve, but I'm confident enough to release it yes. We'll get a new BSP update out in the coming days.

**Comment by fnocci** [comment]
Thanks! Maybe the first step would be to add 'try beta 0.8.0' with a how-to, and solicit feedback in the FAQ in the main documentation page so people do try it when they encounter the "couldn't factory reset" problem. 

It's a little complicated.  For example,  my first few tries, I was using the 'reset' button thinking that was the DFU button, and it's not.  Perhaps this could be the reason for inconsistent feedback, i.e. maybe that's what some other people were doing. 

I'll add a few pictures of how to attach GND to DFU on the breadboard to an update on my forum post, because it's still sitting out on my bench and it's fresh in my mind.  Please feel free to use those in your documentation.   Again, thanks much!

**Comment by TheWiseWalrus** [comment]
Will you be releasing update notes for 0.8? Does it add anything new to the AT command set, or is it primarily bug fixing?

**Comment by microbuilder** [comment]
It's primarily just a bug fix release to try to resolve some random resets of the internal non-volatile config memory.

**Comment by fnocci** [comment]
Just a follow-up open-ended question.

 so I've been reading this: http://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.iotsdk.v0.9.0%2Findex.html and this: https://tools.ietf.org/html/draft-ietf-6lo-btle-03 .  It seems that with custom firmware we could  publish MQTT messages over BLE directly out of the nRF51822 BLE SoC.  Is Adafruit working on this, to integrate those boards into its IoT ecosystem?  It looks as if we'd have to chose whether to use the upper parts of the BLE stack or whether to set it up as an IoT device when loading the firmware.
