### ISSUE TITLE
Source code for the firmware

### ISSUE THREAD

**Issue by ddewaele** [adafruit/Adafruit_BluefruitLE_Firmware#23]
Hi,

Is this firmware source code available somewhere ?

Thx.

**Comment by microbuilder** [comment]
We're not able to publish the source due to copyright restrictions from Nordic, since we use an older SDK that is stricter than some current code from them.

**Comment by fnocci** [comment]
So, say we needed to develop some custom firmware for the nRF51822 chip -- eg. to provide bespoke GAP & GATT services, written using the more recently released Nordic libraries, which we could open source.  And say we wanted said GAP and GATT services to interact with devices connected through the Feather Bluefruit 32u4 board.  Where would we find the information necessary to do this?  If we were privy to the current firmware source -- or at least the module which interacts with the development board -- we might be able to fill in the blanks with help from the schematics and other published information.  Perhaps a tutorial or example application that does this would be helpful.

**Comment by ddewaele** [comment]
Thx a lot for the quick response @microbuilder. Love your excellent guide on https://learn.adafruit.com/introducing-adafruit-ble-bluetooth-low-energy-friend/introduction !

(The guide does mention flashing Arduino sketches a couple of times, although I don't see how this would work with the AdaFruit BLE Friend device as it only contains th nRF51822 chip. Is there a board definition for it allowing us to flash it with Arduino sketches) ?

**Comment by ladyada** [comment]
hiya for both of y'all the answer will be the same, check out the nrf51 arduino board support package - it will let you program the 'raw' chip
https://github.com/sandeepmistry/arduino-nRF5
we didnt write that code, nor do we have a detailed guide on how to use it!

**Comment by fnocci** [comment]
Yay!  Thanks!  I think.  I don't see the Feather 32u4 Bluefruit board (or for that matter any Adafruit board) as being supported in the @sandeepmistry arduino-nRF5 documentation, but I do see several RedBear boards. Maybe the Feather 32u4 Bluefruit is close enough to the supported boards that it will be obvious once we start using that library?  Maybe we'll brick a string of feathers finding out?

**Comment by ladyada** [comment]
it is not really supported because we dont expose a way to program the chip easily, its meant to be used as is only. you can do it, but you're really on your own :)

**Comment by fnocci** [comment]
OK, we'll set the Feather 32u4 Bluefruit aside for fun projects then, maybe reverse engineering some day with hammer and tongs when the spirit moves us.  

Looks like the Feather nRF52 is going to be easier to program the BLE stack on, and thus better for the wireless pH & Temperature monitoring project.  "She turned me on to myNewt!"  Thanks LadyAda!
