### ISSUE TITLE
Limit to bonded devices?

### ISSUE THREAD

**Issue by bolteon** [adafruit/Adafruit_BluefruitLE_Firmware#24]
Hi there, we seem to be running into a limit with bonded devices, is 7 the max?

Is there a way to adjust the max bonded devices? We're trying to bond one peripheral-mode Bluefruit LE via the GAP profile, as an HID, to 15 different centrals.

Conversely, if there another way to initiate bonding other than HID? Seems like we should be able to set a characteristic as "secure" in our GATT and the pairing/bonding process should start upon attempted access?

**Comment by bolteon** [comment]
Bmmp!

Hoping someone can help us out on this...

**Comment by bolteon** [comment]
So rather than answer the question, you just delete my second post?

**Comment by ladyada** [comment]
hiya, don't bump posts - we will get to your answer as soon as we can! :)

**Comment by bolteon** [comment]
Happy to not bump anything, could I get someone to answer me directly? The support email tells me to post on the forum, the forum admin told me to go use someone elses product... This is not the way to handle a company wanting to utilize your products. Would really appreciate a reach out: marko.mandaric@thmgrp.com

**Comment by hathach** [comment]
@bolteon hi, sorry for late response. We are currently really busy with the preparation for the nrf52840 launching. Give us a bit of time, we will check out the code and get back to you when possible. thanks.

**Comment by bolteon** [comment]
Would you guys consider sharing the source behind the stack implementation outside of the NS SDK? What we really really need is the ability to enable a secure characteristic so that we can bond properly, it would solve our above issue as well.

**Comment by ladyada** [comment]
we cannot, it is under NDA and we have not gotten permission to release it from Nordic.

**Comment by bolteon** [comment]
Could we sign an NDA agreeing to not public release? Or, if we could get permission from NS, would that also work? We don't mind doing the leg work ourselves in writing the code but it's 98% there in yours already.

**Comment by ladyada** [comment]
No, that is not possible. we recommend looking at Nordic's API code to implement what you need from scratch, they have many examples!

**Comment by bolteon** [comment]
Could you guys help us out at least in just giving us a version of the firmware that limits bonding to a single connection?

It's literally just adjusting 1 number in the source from what we've read... it would be immensely helpful. Please...

**Comment by ladyada** [comment]
No, that is not possible. we recommend looking at Nordic's API code to implement what you need from scratch, they have many examples

**Comment by hathach** [comment]
@bolteon  how about migrating to feather nrf52. nrf52 is completely open from bootloader to all libraries. It is a bit different, it is preferable if you want to do more complicated or customized your project etc ... nrf51 series is like entry which helps people get started easy with ble.

**Comment by ladyada** [comment]
marko, for your product development needs, purchase dev kits from nordic. we do not do the firmware development or engineering support you require.
