### ISSUE TITLE
BLEFRIEND32 0.8.1 reports incorrect version number

### ISSUE THREAD

**Issue by stonehippo** [adafruit/Adafruit_BluefruitLE_Firmware#30]
I recently updated a V2 Bluefruit LE Friend to the version 0.8.1 firmware when prompted by the Bluefruit app. The OTA DFU went fine, but on reconnection, I was prompted to update the firmware again. A check of the device information showed the Software Revision has this value:

```
0.8.0 - Apr 10 2019
```

I also have a Feather M0 Bluefruit LE, which I also upgraded to latest firmware. This seemed to work fine and reported the expected Software Revision value:

```
0.8.1 - Apr 10 2019
```

Since the LE friend uses the BLEFRIEND32 firmware build, and the M0 used BLESPIFRIEND, I have to assume the former has an incorrect build number. I tried downgrading to the actual 0.8.0 and 0.7.7 versions of BLEFRIEND32, then upgrading again, with the same result. The issue seems to be in the release.

**Comment by hathach** [comment]
@stonehippo thank you very much for raising the issue, it is a typo mistake in the binary release.I have just pushed update. Can you please try it out again :)

**Comment by stonehippo** [comment]
@hathach that did it. Thanks!

**Comment by hathach** [comment]
thanks for testing it out
