### ISSUE TITLE
 Does not work with MDBT40-256RV3

### ISSUE THREAD

**Issue by wwarczak** [adafruit/Adafruit_BluefruitLE_Firmware#32]
I have a problem running the MDBT40-256RV3 module with this firmware in my project.

I have programmed the brand new MDBT40-256RV3 module purchased at https://www.adafruit.com/product/4076:

adalink nrf51822 --programmer stlink --wipe \
--program-hex ./Adafruit_BluefruitLE_Firmware/bootloader/bootloader_nrf52_0008.hex \
--program-hex ./Adafruit_BluefruitLE_Firmware/softdevice/s110_nrf51_8.0.0_softdevice.hex \
--program-hex ./Adafruit_BluefruitLE_Firmware/0.8.0/blespifriend/blespifriend_s110_xxac_0_8_0_170925_blespifriend.hex \
--program-hex ./Adafruit_BluefruitLE_Firmware/0.8.0/blespifriend/blespifriend_s110_xxac_0_8_0_170925_blespifriend_signature.hex

The module is not recognized by the software(https://learn.adafruit.com/adafruit-fea ... le-library), the LEDs do not flash.
 
Test reports the error:

Adafruit Bluefruit AT Command Example
-------------------------------------
Initialising the Bluefruit LE module: OK!
Performing a factory reset:
AT+FACTORYRESET

<- ??
??
Couldn't factory reset

**Comment by ladyada** [comment]
hi, we dont know - could be wiring or hardware issue. we don't support or guarantee any DIY firmware.
