### ISSUE TITLE
Source code for SDEP protocol

### ISSUE THREAD

**Issue by 1461748123** [adafruit/Adafruit_BluefruitLE_Firmware#35]
Hi!

I'm currently working on a project that requires me to process data sent using the Adafruit's SDEP protocol.
I'm not sure if it's possible to open source part of the firmware that involves SDEP? I understand that fully open sourcing the firmware isn't possible due to copyright restrictions from Nordic.

Thanks in advance!

**Comment by ladyada** [comment]
hi it is not possible, we tried discussing it with nordic many times but they could not release use :( please use parsing code here: https://github.com/adafruit/Adafruit_BluefruitLE_nRF51 or here https://github.com/adafruit/Adafruit_CircuitPython_BluefruitSPI
