### ISSUE TITLE
Update history

### ISSUE THREAD

**Issue by collin80** [adafruit/Adafruit_BluefruitLE_Firmware#39]
Can we please get a reasonable list of what changed in the various firmware versions? The lack of source code means that the git binary check ins are basically useless to glean any wisdom. It was said that 0.8.0 was mostly to fix a specific bug related to losing configuration. But, what is 0.8.1? Is it just 0.8.0 out of beta or what does it do?

The last time someone asked this they were directed to a web site. Guess what, that page stops at firmware version 0.7.7. So, it still leaves me shrouded in mystery.

**Comment by hathach** [comment]
Hi, following is the firmware changelog.

```
## 0.8.1

- Fixed incorrect UUID for battery level characteristic

## 0.8.0

- Improve stability of nvm
```

**Comment by collin80** [comment]
Awesome! That's just what everyone needed to figure out whether we all should upgrade or not. Thanks!
