### ISSUE TITLE
SoftDevice s120 or s130 in the works?

### ISSUE THREAD

**Issue by sk1tt1sh** [adafruit/Adafruit_BluefruitLE_Firmware#5]
Well, after attempting to make my bluefruit a central and debricking it a couple times (THANK YOU FOR RASPI INSTRUCTIONS!) I've resigned to the fact that I'm probably going to have to go through the whole nordic process.

I was wondering if you were planning to implement central capabilities for it? I would love to be able to scan for devices with it and dump the data out to serial. There's a load of neat projects that could be done with it!

If you've already started down that road and need another tester please let me know!

Thank you for an awesome fun product! :)

**Comment by microbuilder** [comment]
Sorry there are currently no plans to add Central mode support ... there just isn't enough demand to justify the very significant development effort involved, and Central mode is more appropriate for the upcoming nRF52 chips which have more flash storage than the nRF51822.  We might revisit this at some point in the distant future, but it's not something we're likely to try with the current HW.
