### ISSUE TITLE
iOS writing without response.

### ISSUE THREAD

**Issue by cyrusbowman** [adafruit/Adafruit_BluefruitLE_Firmware#6]
I am unable to write values to the TX characteristic with type: CBCharacteristicWriteType.WithoutResponse, .WithResponse works as expected.

`self.blePeripheral.writeValue(data, forCharacteristic: self.txChar, type: CBCharacteristicWriteType.WithoutResponse)`

I am on 0.7.0 with the blefriend32.

I was using another BLE module (not from adafruit) that had the same issue. They reported to me: `Engineering found had some minor mismatch in the BLE properties that conflicted with iOS` after they fixed it, not sure if that helps any.

Thanks for all the hard work!

**Comment by don** [comment]
The UART service doesn't support write WithoutResponse. Using write WithResponse the correct way. I think this is by design. The hardware *could* support both but doesn't.

Note that the older Bluefruit nRF8001 is the opposite, you must use write WithoutResponse.

I support both by checking the characteristic's properties before writing. For most cases this doesn't effect the app since CoreBluetooth is transparently handing the write response.

    if ((characteristic.properties & CBCharacteristicPropertyWrite) == CBCharacteristicPropertyWrite) {
        [p writeValue:data forCharacteristic:characteristic type:CBCharacteristicWriteWithResponse];
    }
    else if ((characteristic.properties & CBCharacteristicPropertyWriteWithoutResponse) == CBCharacteristicPropertyWriteWithoutResponse) {
        [p writeValue:data forCharacteristic:characteristic type:CBCharacteristicWriteWithoutResponse];
    }

**Comment by microbuilder** [comment]
Thanks for the comment Don!

**Comment by cyrusbowman** [comment]
Thanks @don. I was wanting to write `WithoutResponse` because the TX rates aren't high enough for my application. I need ~500 bytes/sec. I like this module but I am not able to get as fast as write rates as the two others I am using. The others have similar speeds as this one when writing `WithResponse` (~330 bytes/sec). But when writing `WithoutResponse` on the other two modules I am able to get speeds up to 1130 bytes/sec without any data loss, I was hoping this module would support it.

**Comment by microbuilder** [comment]
Have you tried with the 0.7.0 BETA firmware?  It's still a work in progress, but we've been making some meaningful effort to improve speed for the upcoming release.  The UART service is able to hit ~1KB/s, for example, though it of course depends on what's on the other end, and we actually need to push some updates out to the Bluefruit LE Connect apps now since they aren't keeping up with the latest firmware throughput. You can enable optional BETA firmware updates in both the iOS and Android apps in the respective app config screens.

**Comment by cyrusbowman** [comment]
@microbuilder yes I am on 0.7.0 beta. I wrote an app to check the speed. I haven't tried on Android (because I need iOS support) but you'd probably be able to get the 1KB/s you suggest. With iOS's longer connection interval it'd be hard and [maybe not even possible](https://bluegiga.zendesk.com/entries/22400867--HOW-TO-Maximize-throughput-with-BLE-modules) to get 500 bytes/sec when you are writing acknowledged packets (ie. `WithResponse`). But with unacknowledged packets you can send much faster, you just aren't guaranteed delivery. That is what I was hoping to do with this module. There's a TinySine and Serialio module that can do it. I like this module better than those two but until it can send unacknowledged packets I'll have to go with the others.

**Comment by hathach** [comment]
Hi @cyrusbowman,

We just update the beta firmware (also 0.7.0 with build date "Mar 25 2016") to enable support for wirte_without_response and write with reponse. Can you test to see if that work for you ?

If possible please let me know how you to test there, so that we can also do it here.

**Comment by DadoKomar** [comment]
Hello @hathach 

I have enabled beta versions for your BLE software under iOS, but can not see any beta update in App Store. 

Thanks for help.

**Comment by DadoKomar** [comment]
Hello @cyrusbowman 

How to send in data mode without response. I did 660 chars/s with old 070 beta firmware. Just the application on iOS started to fall a lot.

Thnaks

**Comment by hathach** [comment]
@DadoKomar  please try to follow the FAQs here https://learn.adafruit.com/introducing-adafruit-ble-bluetooth-low-energy-friend/faq#faq-10

**Comment by microbuilder** [comment]
There will be an update for the iOS application shortly ... it does currently have problems with really high speed transfers on 0.7.0.  The Android app should be OK if you have access to an Android phone while we finish up the next version of the iOS app, though. Sorry for the delay.

**Comment by microbuilder** [comment]
@DadoKomar This is really a support issue not a feature request or bug report ... can you please post support related questions in the Adafruit support forum?  The support staff generally doesn't monitor the github issues here.

**Comment by DadoKomar** [comment]
Ah, sorry, of course firmware, thought we talking about app. Gonna test new beta.

**Comment by cyrusbowman** [comment]
@hathach Sorry just saw this. Downloaded and tested. Works great. I am able to get ~668 bytes/sec without data loss. Thats sending 20 bytes at an interval of 0.030 sec on iOS. You can probably get it going a little faster with a smaller interval but that suits my needs! Thanks!

@DadoKomar with swift you do blePeripheral.writeValue(DATA, forCharacteristic: CHARACTERISTIC, type: CBCharacteristicWriteType.WithoutResponse)
