### ISSUE TITLE
Firmware source code?

### ISSUE THREAD

**Issue by joseangeljimenez** [adafruit/Adafruit_BluefruitLE_Firmware#7]
Hello,

I wonder if you have or are planning to release the firmware source code with an open or closed license? It'll be a great study material for those of us, like myself, which have invested some time learning the nRF51 platform but which haven't got that far developing BLE code on it?

Thanks for your good work!

**Comment by yjlintw** [comment]
+1, I am also highly interested in that. That will be super helpful, thanks.

**Comment by sprite728** [comment]
Hello, 
I agree with Jose. This will be tremendously helpful to the project I'm working on. I hope to switch my BLE between Central and Peripheral mode.

**Comment by microbuilder** [comment]
Because the source code we use dates back to the earliest SDK releases, the files are unfortunately covered by a restrictive license and we aren't able to release the code.  Nordic has recently changed the SDK terms for some files, and is continuing to move towards more open code, but we would have to migrate the entire codebase to make use exclusively of the latest source which isn't realistic for us at present.  Sorry for the inconvenience, but we have very limited influence over the business decisions the various silicon vendors we work with make.

**Comment by joseangeljimenez** [comment]
@microbuilder Thanks for your response. However, wouldn't it be possible to disclose only the source files developed by you, without the SDK files from Nordic? That way, interested people could download the Nordic SDK and compile the whole project together.

I have been developing for a while on the nRF51822. Would you consider handing over the work of migrating the codebase to the latest (and more open) Nordic SDK? I am sure I could find two-three developers with BLE experience to undertake the required work.

Thanks for taking it into consideration,
Jose A. Jimenez

**Comment by sprite728** [comment]
@microbuilder  I will back @joseangeljimenez 's proposal. I think it would be really helpful if you could share the source files with no SDK from Nordic. I also have some experience with nRF51822, and would like to figure out an option to update the firmware myself. The source files will be helpful for figuring out the communication between ATmega32u4 and nRF51822, and other stuffs.

**Comment by JeanRintoul** [comment]
Agreed to have the code without the SDK available would work. As it stands, it would also be good to change the name of the BLE device? Is this possible without modifying the firmware?

**Comment by ladyada** [comment]
https://learn.adafruit.com/introducing-the-adafruit-bluefruit-spi-breakout/ble-gap#at-plus-gapdevname

**Comment by JeanRintoul** [comment]
Thanks!

**Comment by WayneKeenan** [comment]
Would you be able and willing to share the firmware source code privately?

**Comment by ladyada** [comment]
we cannot share source code privately - we are looking to release it under GPL, ktown will update this thread when thats done. no ETA - plz don't bump.
