### ISSUE TITLE
Add support for characteristic descriptors

### ISSUE THREAD

**Issue by pdev55** [adafruit/Adafruit_BluefruitLE_Firmware#8]
Hi,
I was wondering if you have any plans for adding AT-commands for adding/accessing characteristic descriptors (such as "Presentation Format" or "User Description") to your Bluefruit LE SPI friend firmware.

**Comment by microbuilder** [comment]
We've already filed this as an issue internally and it will be added into a future release.  I'll close this issue since we already have one internally, but thanks for bringing it up.
