### ISSUE TITLE
AT+GATTCHAR only gives four first bytes

### ISSUE THREAD

**Issue by deisterhold** [adafruit/Adafruit_BluefruitLE_Firmware#9]
When using the AT+GATTCHAR command, only the first four bytes are displayed even though it supports up to 20. Also if there could be a way for the MCU to be notified that a service characteristic has been changed instead of having to poll for new data.

**Comment by microbuilder** [comment]
These changes should be implemented in the 0.7.0 release: https://learn.adafruit.com/adafruit-feather-32u4-bluefruit-le/history#version-0-dot-7-0

By indicating the data type for your characteristic it will now be correctly displayed, and there are new callbacks mechanisms (and examples) in the latest release of the nRF51 Arduino library.
